
spring:
  threads:
    virtual:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    username: sa
    password: password
    url: jdbc:h2:file:./database.h2
  jpa:
    hibernate:
      ddl-auto: create-drop
  main:
    web-application-type: servlet
springdoc:
  api-docs:
    path: /v3/api-docs
logging:
  level:
    root: info