spring:
  threads:
    virtual:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    username: sa
    password: password
    url: jdbc:h2:file:./database.h2
  jpa:
    hibernate:
      ddl-auto: create-drop
  main:
    web-application-type: servlet
  ai:
    openai:
      api-key: sk-033969b6f9f14cf0903a294deec5103c
#      chat:
#        options:
#          model: deepseek-reasoner
      base-url: http://localhost:8000
      embedding:
        enabled: false
#    ollama:
#      chat:
#        options:
#          model: deepseek-r1
#        init:
#          pull-model-strategy: when_missing
#        embedding:
#          enabled: false
#      base-url: http://localhost:8000
#      chat:
#        options:
#          model: Llama 3.2
#    anthropic:
#      chat:
#        options:
#          model: Llama-3.2-3B-Instruct-Q4_0.gguf
springdoc:
  api-docs:
    path: /v3/api-docs
logging:
  level:
    root: info